server:
  port: 8001
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ad-service


  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/targul

  datasource:
    url: jdbc:postgresql://localhost:5432/trgladservicedb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

app:
  ads:
    per-page: 4