server:
  port: 8001
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ad-service
  datasource:
    url: jdbc:postgresql://localhost:5432/trgladservicedb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

app:
  ads:
    per-page: 20